apiVersion: v2
name: wordpress
description: Vanilla WordPress + its own MySQL, for the Enact cluster
type: application
version: 0.1.0
appVersion: "latest"
dependencies:
  - name: mysql
    version: "0.1.0"
    repository: "file://charts/mysql"
