apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-wordpress
  labels:
    app.kubernetes.io/name: wordpress
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: wordpress
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: wordpress
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: wordpress
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: WORDPRESS_DB_HOST
              value: {{ include "wordpress.mysqlHost" . }}
            - name: WORDPRESS_DB_NAME
              value: {{ .Values.global.database.name }}
            - name: WORDPRESS_DB_USER
              value: {{ .Values.global.database.user }}
            - name: WORDPRESS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.secretName }}
                  key: wordpress-password
          ports:
            - containerPort: 80
              name: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: wp-content
              mountPath: /var/www/html
            - name: php-uploads
              mountPath: /usr/local/etc/php/conf.d/uploads.ini
              subPath: uploads.ini
            {{- if .Values.privateSite.enabled }}
            - name: private-site
              mountPath: /var/www/html/wp-content/mu-plugins/private-site.php
              subPath: private-site.php
            {{- end }}
      volumes:
        - name: wp-content
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-wordpress
          {{- else }}
          emptyDir: {}
          {{- end }}
        - name: php-uploads
          configMap:
            name: {{ .Release.Name }}-php-uploads
        {{- if .Values.privateSite.enabled }}
        - name: private-site
          configMap:
            name: {{ .Release.Name }}-private-site
        {{- end }}
