{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-wordpress
  labels:
    app.kubernetes.io/name: wordpress
    app.kubernetes.io/instance: {{ .Release.Name }}
  annotations:
    cert-manager.io/cluster-issuer: {{ .Values.ingress.clusterIssuer }}
spec:
  ingressClassName: {{ .Values.ingress.ingressClassName }}
  tls:
    - hosts:
        - {{ required "ingress.hostname is required" .Values.ingress.hostname }}
      secretName: {{ .Release.Name }}-tls
  rules:
    - host: {{ .Values.ingress.hostname }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-wordpress
                port:
                  number: {{ .Values.service.port }}
{{- end }}
